<?php

namespace Container2upEhra;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Luo071zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Luo071z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Luo071z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'circuit' => ['privates', '.errored..service_locator.Luo071z.App\\Entity\\Circuit', NULL, 'Cannot autowire service ".service_locator.Luo071z": it references class "App\\Entity\\Circuit" but no such service exists.'],
            'circuitRepository' => ['privates', 'App\\Repository\\CircuitRepository', 'getCircuitRepositoryService', true],
        ], [
            'circuit' => 'App\\Entity\\Circuit',
            'circuitRepository' => 'App\\Repository\\CircuitRepository',
        ]);
    }
}
