<?php

namespace Container2upEhra;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0Ckzx7KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0Ckzx7K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0Ckzx7K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'circuitTypeRepository' => ['privates', '.errored.uY9RkX.', NULL, 'Cannot determine controller argument for "App\\Controller\\CircuitTypeController::new()": the $circuitTypeRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\CircuitTypeRepository".'],
        ], [
            'circuitTypeRepository' => '?',
        ]);
    }
}
