<?php

namespace Container2upEhra;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WoPKR7nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WoPKR7n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WoPKR7n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'circuitTypeRepository' => ['privates', '.errored.vya1khG', NULL, 'Cannot determine controller argument for "App\\Controller\\CircuitTypeController::index()": the $circuitTypeRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\CircuitTypeRepository".'],
        ], [
            'circuitTypeRepository' => '?',
        ]);
    }
}
