<?php

namespace Container2upEhra;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P8eToqgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p8eToqg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p8eToqg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'resourceTypeRepository' => ['privates', 'App\\Repository\\ResourceTypeRepository', 'getResourceTypeRepositoryService', true],
        ], [
            'resourceTypeRepository' => 'App\\Repository\\ResourceTypeRepository',
        ]);
    }
}
