<?php

namespace Container2upEhra;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResourceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HZec6pw.App\Entity\ResourceType' shared service.
     *
     * @return \App\Entity\ResourceType
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HZec6pw": it references class "App\\Entity\\ResourceType" but no such service exists.');
    }
}
