PRD - Outil de planification de Parcours de soins: App\Controller\ConsultationPlanningController Class Reference
App\Controller\ConsultationPlanningController Class Reference
Public Member Functions
consultationPlanningGet (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR)
This function is the getter of the Controller.
getResourcesScheduled (ManagerRegistry $doctrine, $displayedActivity)
getMaterialResourcesUnavailables (ManagerRegistry $doctrine)
This function get the unavailabitity of the material resources.
getHumanResourceUnavailables (ManagerRegistry $doctrine)
This function get the unavailabitity of the human resources.
getUnavailabity (ManagerRegistry $doctrine)
This function get all the unavailabitity of the material and human resources.
getDisplayedActivitiesJSON (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR)
This function is the getter of the Scheduled Activities from the database.
getAppointmentsJSON (ManagerRegistry $doctrine)
This function is the getter of the Appointments from the database.
getPathway (ManagerRegistry $doctrine, $id)
This function is the getter of the Pathways from the database.
getMaterialResourceScheduledJSON (ManagerRegistry $doctrine)
This function is the getter of the Material Resources to display from the database.
getMaterialCategory (ManagerRegistry $doctrine, $resource)
This function is the getter of the Material Categories to display from the database.
getHumanResourceScheduledJSON (ManagerRegistry $doctrine)
This function is the getter of the Human Resources to display from the database.
getWorkingHours (ManagerRegistry $doctrine, $resource)
This function is the getter of the working hours to display from the database.
getHumanCategory (ManagerRegistry $doctrine, $resource)
This function is the getter of the Human Categories to display from the database.
getPatient (ManagerRegistry $doctrine, $id, $businessHours)
This function is the getter of the Patients from the database.
Public Attributes
$displayedActivities
This variable contains the list of scheduled activities used in several function of the Controller.
$date
Member Function Documentation
consultationPlanningGet()
App\Controller\ConsultationPlanningController::consultationPlanningGet (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR)
This function is the getter of the Controller.
It creates the data used by html an js files by collecting them from the database.
Parameters
ManagerRegistry $doctrine
Returns
JSON File containing the data used by the html and js files.
getAppointmentsJSON()
App\Controller\ConsultationPlanningController::getAppointmentsJSON (ManagerRegistry $doctrine)
This function is the getter of the Appointments from the database.
Parameters
ManagerRegistry $doctrine
Returns
array of the Appointments's data
Referenced by App\Controller\ConsultationPlanningController\consultationPlanningGet().
getDisplayedActivitiesJSON()
App\Controller\ConsultationPlanningController::getDisplayedActivitiesJSON (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR)
This function is the getter of the Scheduled Activities from the database.
Parameters
ManagerRegistry $doctrine
Returns
array all the data of the activites to display
Referenced by App\Controller\ConsultationPlanningController\consultationPlanningGet().
getHumanCategory()
App\Controller\ConsultationPlanningController::getHumanCategory (ManagerRegistry $doctrine, $resource)
This function is the getter of the Human Categories to display from the database.
Parameters
ManagerRegistry $doctrine @parma HumanResource $resource
Returns
array of the resource's data
getHumanResourceScheduledJSON()
App\Controller\ConsultationPlanningController::getHumanResourceScheduledJSON (ManagerRegistry $doctrine)
This function is the getter of the Human Resources to display from the database.
Parameters
ManagerRegistry $doctrine
Returns
array of the resource's data
Referenced by App\Controller\ConsultationPlanningController\consultationPlanningGet().
getHumanResourceUnavailables()
App\Controller\ConsultationPlanningController::getHumanResourceUnavailables (ManagerRegistry $doctrine)
This function get the unavailabitity of the human resources.
Parameters
ManagerRegistry $doctrine
Returns
an array containing the unavailability of the human resources.
Referenced by App\Controller\ConsultationPlanningController\getUnavailabity().
getMaterialCategory()
App\Controller\ConsultationPlanningController::getMaterialCategory (ManagerRegistry $doctrine, $resource)
This function is the getter of the Material Categories to display from the database.
Parameters
ManagerRegistry $doctrine @parma MaterialResource $resource
Returns
array of the resource's data
getMaterialResourceScheduledJSON()
App\Controller\ConsultationPlanningController::getMaterialResourceScheduledJSON (ManagerRegistry $doctrine)
This function is the getter of the Material Resources to display from the database.
Parameters
ManagerRegistry $doctrine
Returns
array of the resource's data
Referenced by App\Controller\ConsultationPlanningController\consultationPlanningGet().
getMaterialResourcesUnavailables()
App\Controller\ConsultationPlanningController::getMaterialResourcesUnavailables (ManagerRegistry $doctrine)
This function get the unavailabitity of the material resources.
Parameters
ManagerRegistry $doctrine
Returns
an array containing the unavailability of the material resources.
Referenced by App\Controller\ConsultationPlanningController\getUnavailabity().
getPathway()
App\Controller\ConsultationPlanningController::getPathway (ManagerRegistry $doctrine, $id)
This function is the getter of the Pathways from the database.
Parameters
ManagerRegistry $doctrine
Returns
array of the pathways's data
getPatient()
App\Controller\ConsultationPlanningController::getPatient (ManagerRegistry $doctrine, $id, $businessHours)
This function is the getter of the Patients from the database.
Parameters
ManagerRegistry $doctrine
$id the id of the patient to get
Returns
array of the patient's data
getResourcesScheduled()
App\Controller\ConsultationPlanningController::getResourcesScheduled (ManagerRegistry $doctrine, $displayedActivity)
Sinon : plusieurs ressources peuvent être associées à une activité programmée on récupère les ressources associées à une activité programmée on les met dans un tableau pour les affecter à l'activité programmée
Referenced by App\Controller\ConsultationPlanningController\getDisplayedActivitiesJSON().
getUnavailabity()
App\Controller\ConsultationPlanningController::getUnavailabity (ManagerRegistry $doctrine)
This function get all the unavailabitity of the material and human resources.
Parameters
ManagerRegistry $doctrine
Returns
an array containing the unavailability
Referenced by App\Controller\ConsultationPlanningController\getDisplayedActivitiesJSON().
getWorkingHours()
App\Controller\ConsultationPlanningController::getWorkingHours (ManagerRegistry $doctrine, $resource)
This function is the getter of the working hours to display from the database.
Parameters
ManagerRegistry $doctrine
Returns
array of the resource's data
The documentation for this class was generated from the following file:
src/Controller/ConsultationPlanningController.php