PRD - Outil de planification de Parcours de soins: App\Controller\SimulationsController Class Reference
App\Controller\SimulationsController Class Reference
Public Member Functions
index (ManagerRegistry $doctrine)
Allow to get the simulation page.
serializeDB (ManagerRegistry $doctrine, bool $delete=false)
Allow to serialize the database into json files.
deSerializeDB (ManagerRegistry $doctrine, int $id)
Allow to deSerialize the database from json files and insert them into the database.
getInfos (ManagerRegistry $doctrine)
Allow to get the simulation infos.
NewSimulation (ManagerRegistry $doctrine)
Allow to create a new simulation.
saveSimulation (ManagerRegistry $doctrine)
Allow to save the current simulation.
changeSimulation (ManagerRegistry $doctrine)
Allow to change the current simulation.
deleteSimulation (ManagerRegistry $doctrine)
Allow to delete a simulation.
Public Attributes
$date
$dateFormatted
Member Function Documentation
changeSimulation()
App\Controller\SimulationsController::changeSimulation (ManagerRegistry $doctrine)
Allow to change the current simulation.
Parameters
ManagerRegistry $doctrine
Returns
JsonResponse
deleteSimulation()
App\Controller\SimulationsController::deleteSimulation (ManagerRegistry $doctrine)
Allow to delete a simulation.
Parameters
ManagerRegistry $doctrine
Returns
JsonResponse
deSerializeDB()
App\Controller\SimulationsController::deSerializeDB (ManagerRegistry $doctrine, int $id)
Allow to deSerialize the database from json files and insert them into the database.
Parameters
ManagerRegistry $doctrine
int $id
Returns
Response
Referenced by App\Controller\SimulationsController\changeSimulation(), and App\Controller\SimulationsController\deleteSimulation().
getInfos()
App\Controller\SimulationsController::getInfos (ManagerRegistry $doctrine)
Allow to get the simulation infos.
Parameters
ManagerRegistry $doctrine
Returns
JsonResponse
Referenced by App\Controller\SimulationsController\index().
index()
App\Controller\SimulationsController::index (ManagerRegistry $doctrine)
Allow to get the simulation page.
Parameters
ManagerRegistry $doctrine
Returns
Response
NewSimulation()
App\Controller\SimulationsController::NewSimulation (ManagerRegistry $doctrine)
Allow to create a new simulation.
Parameters
ManagerRegistry $doctrine
Returns
JsonResponse
saveSimulation()
App\Controller\SimulationsController::saveSimulation (ManagerRegistry $doctrine)
Allow to save the current simulation.
Parameters
ManagerRegistry $doctrine
Returns
JsonResponse
serializeDB()
App\Controller\SimulationsController::serializeDB (ManagerRegistry $doctrine, bool $delete = false)
Allow to serialize the database into json files.
Parameters
ManagerRegistry $doctrine
bool $delete
Returns
Response
Referenced by App\Controller\SimulationsController\changeSimulation(), App\Controller\SimulationsController\NewSimulation(), and App\Controller\SimulationsController\saveSimulation().
The documentation for this class was generated from the following file:
src/Controller/SimulationsController.php