PRD - Outil de planification de Parcours de soins: App\Controller\StatisticsController Class Reference
App\Controller\StatisticsController Class Reference
Public Member Functions
index (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR)
Allows to get stats.
getResourcesScheduled (ManagerRegistry $doctrine, $displayedActivity)
Allows to get the resouces scheduled for a given activity.
getDisplayedActivitiesJSON (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR)
This function is the getter of the Scheduled Activities from the database.
getHumanResourceScheduledJSON (ManagerRegistry $doctrine)
This function is the getter of the Human Resources from the database.
getWorkingHours (ManagerRegistry $doctrine, $resource)
This function is the getter of the working hours to display from the database.
getMaterialResourceScheduledJSON (ManagerRegistry $doctrine)
This function is the getter of the material resources to display from the database.
getAppointmentsJSON (ManagerRegistry $doctrine)
This function is the getter of the appointments to display from the database.
getOccupancyRates (ManagerRegistry $doctrine)
This function is the getter of the occupancy rates to display from the database.
Public Attributes
$date
$dateFormatted
Member Function Documentation
getAppointmentsJSON()
App\Controller\StatisticsController::getAppointmentsJSON (ManagerRegistry $doctrine)
This function is the getter of the appointments to display from the database.
Parameters
ManagerRegistry $doctrine
Returns
array of the resource's data
Referenced by App\Controller\StatisticsController\index().
getDisplayedActivitiesJSON()
App\Controller\StatisticsController::getDisplayedActivitiesJSON (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR)
This function is the getter of the Scheduled Activities from the database.
Parameters
ManagerRegistry $doctrine
Returns
array all the data of the activites to display
Referenced by App\Controller\StatisticsController\index().
getHumanResourceScheduledJSON()
App\Controller\StatisticsController::getHumanResourceScheduledJSON (ManagerRegistry $doctrine)
This function is the getter of the Human Resources from the database.
Parameters
ManagerRegistry $doctrine
Returns
array all the data of the human resources to display
Referenced by App\Controller\StatisticsController\index().
getMaterialResourceScheduledJSON()
App\Controller\StatisticsController::getMaterialResourceScheduledJSON (ManagerRegistry $doctrine)
This function is the getter of the material resources to display from the database.
Parameters
ManagerRegistry $doctrine
Returns
array of the resource's data
Referenced by App\Controller\StatisticsController\index().
getOccupancyRates()
App\Controller\StatisticsController::getOccupancyRates (ManagerRegistry $doctrine)
This function is the getter of the occupancy rates to display from the database.
Parameters
ManagerRegistry $doctrine
Returns
array of the resource's data
BEGINNING OF THE SLOT CALCULATION
Referenced by App\Controller\StatisticsController\index().
getResourcesScheduled()
App\Controller\StatisticsController::getResourcesScheduled (ManagerRegistry $doctrine, $displayedActivity)
Allows to get the resouces scheduled for a given activity.
Parameters
ManagerRegistry $doctrine
ScheduledActivityRepository $SAR
Returns
JsonResponse
Sinon : plusieurs ressources peuvent être associées à une activité programmée on récupère les ressources associées à une activité programmée on les met dans un tableau pour les affecter à l'activité programmée
Referenced by App\Controller\StatisticsController\getDisplayedActivitiesJSON().
getWorkingHours()
App\Controller\StatisticsController::getWorkingHours (ManagerRegistry $doctrine, $resource)
This function is the getter of the working hours to display from the database.
Parameters
ManagerRegistry $doctrine
Returns
array of the resource's data
index()
App\Controller\StatisticsController::index (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR)
Allows to get stats.
Parameters
ManagerRegistry $doctrine
ScheduledActivityRepository $SAR
Returns
Response
The documentation for this class was generated from the following file:
src/Controller/StatisticsController.php