PRD - Outil de planification de Parcours de soins: App\Controller\PathwayController Class Reference
App\Controller\PathwayController Class Reference
Public Member Functions
listHumanResourcesJSON (ManagerRegistry $doctrine)
listMaterialResourcesJSON (ManagerRegistry $doctrine)
pathwayJSON (Pathway $pathway, ManagerRegistry $doctrine)
listTargetsJSON ($pathway, ManagerRegistry $doctrine)
pathwayGet (PathwayRepository $pathwayRepository, ManagerRegistry $doctrine, Request $request, PaginatorInterface $paginator)
pathwayEditPage (Request $request, PathwayRepository $pathwayRepository, ManagerRegistry $doctrine, int $id)
pathwayAddPage (Request $request, PathwayRepository $pathwayRepository, ManagerRegistry $doctrine)
pathwayAdd (Request $request, PathwayRepository $pathwayRepository, ManagerRegistry $doctrine)
show (Pathway $pathway)
pathwayEdit (Request $request, ManagerRegistry $doctrine)
pathwayDelete (Request $request, ManagerRegistry $doctrine)
getActivitiesByPathwayId (ManagerRegistry $doctrine)
sortActivities ($activityArray, $arraySuccessor, ManagerRegistry $doctrine)
checkDuplicate ($activities)
activityToArray (ManagerRegistry $doctrine, $activity, $HRCRequired, $MRCRequired)
getAppointmentsByPathwayId (ManagerRegistry $doctrine)
autocompletePathway (Request $request, PathwayRepository $pathwayRepository)
Member Function Documentation
listHumanResourcesJSON()
App\Controller\PathwayController::listHumanResourcesJSON (ManagerRegistry $doctrine)
Permet de créer un objet json a partir d'une liste de categorie de ressource humaine
Referenced by App\Controller\PathwayController\pathwayAddPage(), App\Controller\PathwayController\pathwayEditPage(), and App\Controller\PathwayController\pathwayGet().
listMaterialResourcesJSON()
App\Controller\PathwayController::listMaterialResourcesJSON (ManagerRegistry $doctrine)
Permet de créer un objet json a partir d'une liste de categorie de ressource materielle
Referenced by App\Controller\PathwayController\pathwayAddPage(), App\Controller\PathwayController\pathwayEditPage(), and App\Controller\PathwayController\pathwayGet().
listTargetsJSON()
App\Controller\PathwayController::listTargetsJSON ($pathway, ManagerRegistry $doctrine)
Permet de créer un objet json contenant les targets d'un pathway
Referenced by App\Controller\PathwayController\pathwayEditPage().
pathwayAdd()
App\Controller\PathwayController::pathwayAdd (Request $request, PathwayRepository $pathwayRepository, ManagerRegistry $doctrine)
Ajoute dans la base de données : Ajoute un parcours
Ajoute les activités liées a ce parcours Ajoute les successors liés aux activités Ajoute les ressources humaines et materielles liées aux activités
route : "/pathway/add"
pathwayAddPage()
App\Controller\PathwayController::pathwayAddPage (Request $request, PathwayRepository $pathwayRepository, ManagerRegistry $doctrine)
Redirige vers la page d'ajout d'un parcours route : "/pathway/add"
pathwayDelete()
App\Controller\PathwayController::pathwayDelete (Request $request, ManagerRegistry $doctrine)
Order of deletion : 1) HumanResourceScheduled MaterialResourceScheduled ActivityHumanResource ActvityMaterialResource Successor 2) ScheduledActivity 3) Appointment Activity 4) Pathway
pathwayEdit()
App\Controller\PathwayController::pathwayEdit (Request $request, ManagerRegistry $doctrine)
Editing pathway method
pathwayEditPage()
App\Controller\PathwayController::pathwayEditPage (Request $request, PathwayRepository $pathwayRepository, ManagerRegistry $doctrine, int $id)
Redirige vers la page d'édition d'un parcours route : "/pathway/edit/{id}"
pathwayGet()
App\Controller\PathwayController::pathwayGet (PathwayRepository $pathwayRepository, ManagerRegistry $doctrine, Request $request, PaginatorInterface $paginator)
Redirige vers la page qui liste les utilisateurs route : "/pathways"
pathwayJSON()
App\Controller\PathwayController::pathwayJSON (Pathway $pathway, ManagerRegistry $doctrine)
Permet de créer un objet json a partir d'une entité de type pathway
$activityHumanResourceRepo = new ActivityHumanResourceRepository($this->getDoctrine()); $materialResourceCategoryRepo = new MaterialResourceCategoryRepository($this->getDoctrine()); $materialResourceCategories = $materialResourceCategoryRepo->findAll(); $materialResourceCategoriesArray = array(); if ($materialResourceCategories != null) { foreach ($materialResourceCategories as $materialResourceCategory) { $materialResourceCategoriesArray[] = array('id' => strval($materialResourceCategory->getId()), 'categoryname' => $materialResourceCategory->getCategoryname(),); } }
Referenced by App\Controller\PathwayController\pathwayEditPage().
The documentation for this class was generated from the following file:
src/Controller/PathwayController.php