PRD - Outil de planification de Parcours de soins: App\Controller\ModificationPlanningController Class Reference
App\Controller\ModificationPlanningController Class Reference
Public Member Functions
modificationPlanningGet (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR)
modificationPlanningValidation (Request $request, AppointmentRepository $appointmentRepository, ActivityRepository $activityRepository, ScheduledActivityRepository $scheduledActivityRepository, HumanResourceScheduledRepository $humanResourceScheduledRepository, MaterialResourceScheduledRepository $materialResourceScheduledRepository, ManagerRegistry $doctrine, EntityManagerInterface $entityManager)
getModifications (ManagerRegistry $doctrine)
modificationAdd ($dateModified, $idUser, $doctrine)
modificationDeleteOnUnload (Request $request, ManagerRegistry $doctrine, $username='')
getSuccessorsArray ($successorsArray, ManagerRegistry $doctrine, $idactivity)
getActivitiesArray ($activitiesArray, ManagerRegistry $doctrine, $idpathway)
getInformationsByDateArray (ManagerRegistry $doctrine, $date, ActivityRepository $activityRepository)
getHumanResourcesJSON (ManagerRegistry $doctrine)
getMaterialResourcesJSON (ManagerRegistry $doctrine)
getActivityHumanResources (ManagerRegistry $doctrine)
getActivityMaterialResources (ManagerRegistry $doctrine)
getHumanResourcesScheduled (ManagerRegistry $doctrine)
getMaterialResourcesScheduled (ManagerRegistry $doctrine)
getScheduledActivityJSON (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR, $date)
getCategoryOfMaterialResource (ManagerRegistry $doctrine)
getCategoryOfHumanResource (ManagerRegistry $doctrine)
getCategoryMaterialResource (ManagerRegistry $doctrine)
getCategoryHumanResource (ManagerRegistry $doctrine)
getPatient (ManagerRegistry $doctrine, $id)
getPathway (ManagerRegistry $doctrine, $id, ActivityRepository $activityRepository)
getWorkingHours (ManagerRegistry $doctrine, $resource)
getMaterialResourcesUnavailables (ManagerRegistry $doctrine)
getHumanResourceUnavailables (ManagerRegistry $doctrine)
getUnavailabity (ManagerRegistry $doctrine)
GetAddPlanning (ManagerRegistry $doctrine, ActivityRepository $activityRepository)
GetAutoAddInfos (ManagerRegistry $doctrine)
GetErrorsInfos (ManagerRegistry $doctrine, ActivityRepository $activityRepository)
Public Attributes
$dateModified
Detailed Description
Modification planning controller
Member Function Documentation
getActivitiesArray()
App\Controller\ModificationPlanningController::getActivitiesArray ($activitiesArray, ManagerRegistry $doctrine, $idpathway)
This function recover all the activities from the database and return the data in a JSON format for JS
Returns
activitiesArrayJSON an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\getInformationsByDateArray().
getActivityHumanResources()
App\Controller\ModificationPlanningController::getActivityHumanResources (ManagerRegistry $doctrine)
This function recover all the relationships between each activity and each of its associated human resources and return the data in a JSON format for JS
Returns
activitiesHumanResourcesArrayJSON an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\getPathway(), and App\Controller\ModificationPlanningController\getScheduledActivityJSON().
getActivityMaterialResources()
App\Controller\ModificationPlanningController::getActivityMaterialResources (ManagerRegistry $doctrine)
This function recover all the relationships between each activity and each of its associated material resources and return the data in a JSON format for JS
Returns
activitiesMaterialResourcesArrayJSON an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\getPathway(), and App\Controller\ModificationPlanningController\getScheduledActivityJSON().
getCategoryHumanResource()
App\Controller\ModificationPlanningController::getCategoryHumanResource (ManagerRegistry $doctrine)
This function recover all category human resource from the database and return an array in JSON format for JS
Returns
humanResourcesCategoryArrayJSON an array in JSON format with all the data
getCategoryMaterialResource()
App\Controller\ModificationPlanningController::getCategoryMaterialResource (ManagerRegistry $doctrine)
This function recover all category material resource from the database and return an array in JSON format for JS
Returns
materialResourcesCategoryArrayJSON an array in JSON format with all the data
getCategoryOfHumanResource()
App\Controller\ModificationPlanningController::getCategoryOfHumanResource (ManagerRegistry $doctrine)
This function recover all category of human resource from the database and return an array in JSON format for JS
Returns
categoryOfHumanResourceArrayJSON an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\getHumanResourcesJSON().
getCategoryOfMaterialResource()
App\Controller\ModificationPlanningController::getCategoryOfMaterialResource (ManagerRegistry $doctrine)
This function recover all category of material resource from the database and return an array in JSON format for JS
Returns
categoryOfMaterialResourceArrayJSON an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\getMaterialResourcesJSON().
getHumanResourcesJSON()
App\Controller\ModificationPlanningController::getHumanResourcesJSON (ManagerRegistry $doctrine)
This function recover all the human resources and return the data in a JSON format for JS
Returns
humanResourcesArrayJson an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\modificationPlanningGet().
getHumanResourcesScheduled()
App\Controller\ModificationPlanningController::getHumanResourcesScheduled (ManagerRegistry $doctrine)
This function recover all the relationships between each activity and each of its associated human resources and return the data in a JSON format for JS
Returns
activitiesHumanResourcesArrayJSON an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\getScheduledActivityJSON().
getHumanResourceUnavailables()
App\Controller\ModificationPlanningController::getHumanResourceUnavailables (ManagerRegistry $doctrine)
This function get the unavailabitity of the human resources.
Parameters
ManagerRegistry $doctrine
Returns
an array containing the unavailability of the human resources.
Referenced by App\Controller\ModificationPlanningController\getUnavailabity().
getInformationsByDateArray()
App\Controller\ModificationPlanningController::getInformationsByDateArray (ManagerRegistry $doctrine, $date, ActivityRepository $activityRepository)
This function recover all the appointments for a date given and return the data in a JSON format for JS
Returns
appointmentsArrayJSON an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\modificationPlanningValidation().
getMaterialResourcesJSON()
App\Controller\ModificationPlanningController::getMaterialResourcesJSON (ManagerRegistry $doctrine)
This function recover all the material resources and return the data in a JSON format for JS
Returns
materialResourcesArrayJson an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\modificationPlanningGet().
getMaterialResourcesScheduled()
App\Controller\ModificationPlanningController::getMaterialResourcesScheduled (ManagerRegistry $doctrine)
This function recover all the relationships between each activity and each of its associated material resources and return the data in a JSON format for JS
Returns
activitiesMaterialResourcesArrayJSON an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\getScheduledActivityJSON().
getMaterialResourcesUnavailables()
App\Controller\ModificationPlanningController::getMaterialResourcesUnavailables (ManagerRegistry $doctrine)
This function get the unavailabitity of the material resources.
Parameters
ManagerRegistry $doctrine
Returns
an array containing the unavailability of the material resources.
Referenced by App\Controller\ModificationPlanningController\getUnavailabity().
getModifications()
App\Controller\ModificationPlanningController::getModifications (ManagerRegistry $doctrine)
This function verifies if a modification for this date is already in progress
getPathway()
App\Controller\ModificationPlanningController::getPathway (ManagerRegistry $doctrine, $id, ActivityRepository $activityRepository)
This function recover a pathway by his identifier from the database and return an array with the data
Returns
pathwayArray an array with all data related to it
getPatient()
App\Controller\ModificationPlanningController::getPatient (ManagerRegistry $doctrine, $id)
This function recover a patient by his identifier from the database and return an array with the data
Returns
patientArray an array with all data related to it
getScheduledActivityJSON()
App\Controller\ModificationPlanningController::getScheduledActivityJSON (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR, $date)
This function set all data needed for create all event in fullcalendar corresponding to each scheduled activity
Returns
scheduledActivitiesArrayJSON an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\modificationPlanningGet().
getSuccessorsArray()
App\Controller\ModificationPlanningController::getSuccessorsArray ($successorsArray, ManagerRegistry $doctrine, $idactivity)
This function recover all the successors from the database and return the data in a JSON format for JS
Returns
successorsArrayJSON an array in JSON format with all the data
Referenced by App\Controller\ModificationPlanningController\getInformationsByDateArray().
getUnavailabity()
App\Controller\ModificationPlanningController::getUnavailabity (ManagerRegistry $doctrine)
This function get all the unavailabitity of the material and human resources.
Parameters
ManagerRegistry $doctrine
Returns
an array containing the unavailability
Referenced by App\Controller\ModificationPlanningController\getScheduledActivityJSON().
getWorkingHours()
App\Controller\ModificationPlanningController::getWorkingHours (ManagerRegistry $doctrine, $resource)
This function is the getter of the working hours to display from the database.
Parameters
ManagerRegistry $doctrine
Returns
array of the resource's data
modificationAdd()
App\Controller\ModificationPlanningController::modificationAdd ($dateModified, $idUser, $doctrine)
This function add a data to the table Modification for the user
Referenced by App\Controller\ModificationPlanningController\modificationPlanningGet().
modificationDeleteOnUnload()
App\Controller\ModificationPlanningController::modificationDeleteOnUnload (Request $request, ManagerRegistry $doctrine, $username = '')
This function delete the data modification when the user leave modification planning and then redirect to consultation planning
Referenced by App\Controller\ModificationPlanningController\modificationPlanningValidation().
modificationPlanningGet()
App\Controller\ModificationPlanningController::modificationPlanningGet (ManagerRegistry $doctrine, ScheduledActivityRepository $SAR)
This function build the main page of modification planning and give many informations
modificationPlanningValidation()
App\Controller\ModificationPlanningController::modificationPlanningValidation (Request $request, AppointmentRepository $appointmentRepository, ActivityRepository $activityRepository, ScheduledActivityRepository $scheduledActivityRepository, HumanResourceScheduledRepository $humanResourceScheduledRepository, MaterialResourceScheduledRepository $materialResourceScheduledRepository, ManagerRegistry $doctrine, EntityManagerInterface $entityManager)
This method recover all informations from modification planning and update database
The documentation for this class was generated from the following file:
src/Controller/ModificationPlanningController.php