<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220627133635 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX IDX_FB60CBBC7DF4E972');
        $this->addSql('DROP INDEX IDX_FB60CBBC81C06096');
        $this->addSql('CREATE TEMPORARY TABLE __temp__achr AS SELECT id, activity_id, categoryhumanresource_id FROM achr');
        $this->addSql('DROP TABLE achr');
        $this->addSql('CREATE TABLE achr (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, activity_id INTEGER NOT NULL, categoryhumanresource_id INTEGER NOT NULL, CONSTRAINT FK_FB60CBBC81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_FB60CBBC7DF4E972 FOREIGN KEY (categoryhumanresource_id) REFERENCES category_human_resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO achr (id, activity_id, categoryhumanresource_id) SELECT id, activity_id, categoryhumanresource_id FROM __temp__achr');
        $this->addSql('DROP TABLE __temp__achr');
        $this->addSql('CREATE INDEX IDX_FB60CBBC7DF4E972 ON achr (categoryhumanresource_id)');
        $this->addSql('CREATE INDEX IDX_FB60CBBC81C06096 ON achr (activity_id)');
        $this->addSql('DROP INDEX IDX_86173FF97DF85AB');
        $this->addSql('DROP INDEX IDX_86173FF981C06096');
        $this->addSql('CREATE TEMPORARY TABLE __temp__acmr AS SELECT id, activity_id, categorymaterialresource_id FROM acmr');
        $this->addSql('DROP TABLE acmr');
        $this->addSql('CREATE TABLE acmr (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, activity_id INTEGER NOT NULL, categorymaterialresource_id INTEGER NOT NULL, CONSTRAINT FK_86173FF981C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_86173FF97DF85AB FOREIGN KEY (categorymaterialresource_id) REFERENCES category_material_resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO acmr (id, activity_id, categorymaterialresource_id) SELECT id, activity_id, categorymaterialresource_id FROM __temp__acmr');
        $this->addSql('DROP TABLE __temp__acmr');
        $this->addSql('CREATE INDEX IDX_86173FF97DF85AB ON acmr (categorymaterialresource_id)');
        $this->addSql('CREATE INDEX IDX_86173FF981C06096 ON acmr (activity_id)');
        $this->addSql('DROP INDEX IDX_6D3A392581C06096');
        $this->addSql('DROP INDEX IDX_6D3A3925F3DA7551');
        $this->addSql('CREATE TEMPORARY TABLE __temp__ap AS SELECT id, pathway_id, activity_id, activityorder, delayminafter, delaymaxafter FROM ap');
        $this->addSql('DROP TABLE ap');
        $this->addSql('CREATE TABLE ap (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, pathway_id INTEGER NOT NULL, activity_id INTEGER NOT NULL, activityorder INTEGER NOT NULL, delayminafter INTEGER NOT NULL, delaymaxafter INTEGER NOT NULL, CONSTRAINT FK_6D3A3925F3DA7551 FOREIGN KEY (pathway_id) REFERENCES pathway (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_6D3A392581C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO ap (id, pathway_id, activity_id, activityorder, delayminafter, delaymaxafter) SELECT id, pathway_id, activity_id, activityorder, delayminafter, delaymaxafter FROM __temp__ap');
        $this->addSql('DROP TABLE __temp__ap');
        $this->addSql('CREATE INDEX IDX_6D3A392581C06096 ON ap (activity_id)');
        $this->addSql('CREATE INDEX IDX_6D3A3925F3DA7551 ON ap (pathway_id)');
        $this->addSql('DROP INDEX IDX_A6FF5DD47DF4E972');
        $this->addSql('DROP INDEX IDX_A6FF5DD458A652CC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__chr AS SELECT id, humanresource_id, categoryhumanresource_id FROM chr');
        $this->addSql('DROP TABLE chr');
        $this->addSql('CREATE TABLE chr (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, humanresource_id INTEGER NOT NULL, categoryhumanresource_id INTEGER NOT NULL, CONSTRAINT FK_A6FF5DD458A652CC FOREIGN KEY (humanresource_id) REFERENCES human_resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_A6FF5DD47DF4E972 FOREIGN KEY (categoryhumanresource_id) REFERENCES category_human_resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO chr (id, humanresource_id, categoryhumanresource_id) SELECT id, humanresource_id, categoryhumanresource_id FROM __temp__chr');
        $this->addSql('DROP TABLE __temp__chr');
        $this->addSql('CREATE INDEX IDX_A6FF5DD47DF4E972 ON chr (categoryhumanresource_id)');
        $this->addSql('CREATE INDEX IDX_A6FF5DD458A652CC ON chr (humanresource_id)');
        $this->addSql('DROP INDEX IDX_90E2810297FB7789');
        $this->addSql('DROP INDEX IDX_90E2810258A652CC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hri AS SELECT id, humanresource_id, indisponibility_id FROM hri');
        $this->addSql('DROP TABLE hri');
        $this->addSql('CREATE TABLE hri (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, humanresource_id INTEGER NOT NULL, indisponibility_id INTEGER NOT NULL, CONSTRAINT FK_90E2810258A652CC FOREIGN KEY (humanresource_id) REFERENCES human_resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_90E2810297FB7789 FOREIGN KEY (indisponibility_id) REFERENCES indisponibilities (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO hri (id, humanresource_id, indisponibility_id) SELECT id, humanresource_id, indisponibility_id FROM __temp__hri');
        $this->addSql('DROP TABLE __temp__hri');
        $this->addSql('CREATE INDEX IDX_90E2810297FB7789 ON hri (indisponibility_id)');
        $this->addSql('CREATE INDEX IDX_90E2810258A652CC ON hri (humanresource_id)');
        $this->addSql('DROP INDEX IDX_B604C7357CF91857');
        $this->addSql('DROP INDEX IDX_B604C73558A652CC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hrsa AS SELECT id, humanresource_id, scheduledactivity_id FROM hrsa');
        $this->addSql('DROP TABLE hrsa');
        $this->addSql('CREATE TABLE hrsa (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, humanresource_id INTEGER NOT NULL, scheduledactivity_id INTEGER NOT NULL, CONSTRAINT FK_B604C73558A652CC FOREIGN KEY (humanresource_id) REFERENCES human_resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B604C7357CF91857 FOREIGN KEY (scheduledactivity_id) REFERENCES scheduled_activity (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO hrsa (id, humanresource_id, scheduledactivity_id) SELECT id, humanresource_id, scheduledactivity_id FROM __temp__hrsa');
        $this->addSql('DROP TABLE __temp__hrsa');
        $this->addSql('CREATE INDEX IDX_B604C7357CF91857 ON hrsa (scheduledactivity_id)');
        $this->addSql('CREATE INDEX IDX_B604C73558A652CC ON hrsa (humanresource_id)');
        $this->addSql('DROP INDEX IDX_D61F2C4797FB7789');
        $this->addSql('DROP INDEX IDX_D61F2C474A4B113F');
        $this->addSql('CREATE TEMPORARY TABLE __temp__imr AS SELECT id, materialresource_id, indisponibility_id FROM imr');
        $this->addSql('DROP TABLE imr');
        $this->addSql('CREATE TABLE imr (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, materialresource_id INTEGER NOT NULL, indisponibility_id INTEGER NOT NULL, CONSTRAINT FK_D61F2C474A4B113F FOREIGN KEY (materialresource_id) REFERENCES material_resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_D61F2C4797FB7789 FOREIGN KEY (indisponibility_id) REFERENCES indisponibilities (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO imr (id, materialresource_id, indisponibility_id) SELECT id, materialresource_id, indisponibility_id FROM __temp__imr');
        $this->addSql('DROP TABLE __temp__imr');
        $this->addSql('CREATE INDEX IDX_D61F2C4797FB7789 ON imr (indisponibility_id)');
        $this->addSql('CREATE INDEX IDX_D61F2C474A4B113F ON imr (materialresource_id)');
        $this->addSql('DROP INDEX IDX_FA49D0B47DF85AB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__material_resource AS SELECT id, categorymaterialresource_id, materialresourcename, available FROM material_resource');
        $this->addSql('DROP TABLE material_resource');
        $this->addSql('CREATE TABLE material_resource (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, categorymaterialresource_id INTEGER NOT NULL, materialresourcename VARCHAR(255) NOT NULL, available BOOLEAN NOT NULL, CONSTRAINT FK_FA49D0B47DF85AB FOREIGN KEY (categorymaterialresource_id) REFERENCES category_material_resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO material_resource (id, categorymaterialresource_id, materialresourcename, available) SELECT id, categorymaterialresource_id, materialresourcename, available FROM __temp__material_resource');
        $this->addSql('DROP TABLE __temp__material_resource');
        $this->addSql('CREATE INDEX IDX_FA49D0B47DF85AB ON material_resource (categorymaterialresource_id)');
        $this->addSql('DROP INDEX IDX_EF6425D2A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__modification AS SELECT id, user_id, datemodif, modified FROM modification');
        $this->addSql('DROP TABLE modification');
        $this->addSql('CREATE TABLE modification (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, datemodif DATE NOT NULL, modified BOOLEAN NOT NULL, CONSTRAINT FK_EF6425D2A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO modification (id, user_id, datemodif, modified) SELECT id, user_id, datemodif, modified FROM __temp__modification');
        $this->addSql('DROP TABLE __temp__modification');
        $this->addSql('CREATE INDEX IDX_EF6425D2A76ED395 ON modification (user_id)');
        $this->addSql('DROP INDEX IDX_81DA37077CF91857');
        $this->addSql('DROP INDEX IDX_81DA37074A4B113F');
        $this->addSql('CREATE TEMPORARY TABLE __temp__mrsa AS SELECT id, materialresource_id, scheduledactivity_id FROM mrsa');
        $this->addSql('DROP TABLE mrsa');
        $this->addSql('CREATE TABLE mrsa (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, materialresource_id INTEGER NOT NULL, scheduledactivity_id INTEGER NOT NULL, CONSTRAINT FK_81DA37074A4B113F FOREIGN KEY (materialresource_id) REFERENCES material_resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_81DA37077CF91857 FOREIGN KEY (scheduledactivity_id) REFERENCES scheduled_activity (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO mrsa (id, materialresource_id, scheduledactivity_id) SELECT id, materialresource_id, scheduledactivity_id FROM __temp__mrsa');
        $this->addSql('DROP TABLE __temp__mrsa');
        $this->addSql('CREATE INDEX IDX_81DA37077CF91857 ON mrsa (scheduledactivity_id)');
        $this->addSql('CREATE INDEX IDX_81DA37074A4B113F ON mrsa (materialresource_id)');
        $this->addSql('DROP INDEX IDX_3EE31A35F3DA7551');
        $this->addSql('DROP INDEX IDX_3EE31A356B899279');
        $this->addSql('CREATE TEMPORARY TABLE __temp__pp AS SELECT id, patient_id, pathway_id FROM pp');
        $this->addSql('DROP TABLE pp');
        $this->addSql('CREATE TABLE pp (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, patient_id INTEGER NOT NULL, pathway_id INTEGER NOT NULL, CONSTRAINT FK_3EE31A356B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3EE31A35F3DA7551 FOREIGN KEY (pathway_id) REFERENCES pathway (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO pp (id, patient_id, pathway_id) SELECT id, patient_id, pathway_id FROM __temp__pp');
        $this->addSql('DROP TABLE __temp__pp');
        $this->addSql('CREATE INDEX IDX_3EE31A35F3DA7551 ON pp (pathway_id)');
        $this->addSql('CREATE INDEX IDX_3EE31A356B899279 ON pp (patient_id)');
        $this->addSql('DROP INDEX IDX_DDA14B856B899279');
        $this->addSql('DROP INDEX IDX_DDA14B8581C06096');
        $this->addSql('CREATE TEMPORARY TABLE __temp__scheduled_activity AS SELECT id, activity_id, patient_id, startdatetime, enddatetime FROM scheduled_activity');
        $this->addSql('DROP TABLE scheduled_activity');
        $this->addSql('CREATE TABLE scheduled_activity (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, activity_id INTEGER NOT NULL, patient_id INTEGER NOT NULL, startdatetime DATETIME NOT NULL, enddatetime DATETIME NOT NULL, CONSTRAINT FK_DDA14B8581C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_DDA14B856B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO scheduled_activity (id, activity_id, patient_id, startdatetime, enddatetime) SELECT id, activity_id, patient_id, startdatetime, enddatetime FROM __temp__scheduled_activity');
        $this->addSql('DROP TABLE __temp__scheduled_activity');
        $this->addSql('CREATE INDEX IDX_DDA14B856B899279 ON scheduled_activity (patient_id)');
        $this->addSql('CREATE INDEX IDX_DDA14B8581C06096 ON scheduled_activity (activity_id)');
        $this->addSql('DROP INDEX IDX_D72CDC3D899D27DB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__working_hours AS SELECT id, workinghours_id, startdatetime, enddatetime FROM working_hours');
        $this->addSql('DROP TABLE working_hours');
        $this->addSql('CREATE TABLE working_hours (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, humanresource_id INTEGER NOT NULL, startdatetime DATETIME NOT NULL, enddatetime DATETIME NOT NULL, CONSTRAINT FK_D72CDC3D58A652CC FOREIGN KEY (humanresource_id) REFERENCES human_resource (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO working_hours (id, humanresource_id, startdatetime, enddatetime) SELECT id, workinghours_id, startdatetime, enddatetime FROM __temp__working_hours');
        $this->addSql('DROP TABLE __temp__working_hours');
        $this->addSql('CREATE INDEX IDX_D72CDC3D58A652CC ON working_hours (humanresource_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX IDX_FB60CBBC81C06096');
        $this->addSql('DROP INDEX IDX_FB60CBBC7DF4E972');
        $this->addSql('CREATE TEMPORARY TABLE __temp__achr AS SELECT id, activity_id, categoryhumanresource_id FROM achr');
        $this->addSql('DROP TABLE achr');
        $this->addSql('CREATE TABLE achr (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, activity_id INTEGER NOT NULL, categoryhumanresource_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO achr (id, activity_id, categoryhumanresource_id) SELECT id, activity_id, categoryhumanresource_id FROM __temp__achr');
        $this->addSql('DROP TABLE __temp__achr');
        $this->addSql('CREATE INDEX IDX_FB60CBBC81C06096 ON achr (activity_id)');
        $this->addSql('CREATE INDEX IDX_FB60CBBC7DF4E972 ON achr (categoryhumanresource_id)');
        $this->addSql('DROP INDEX IDX_86173FF981C06096');
        $this->addSql('DROP INDEX IDX_86173FF97DF85AB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__acmr AS SELECT id, activity_id, categorymaterialresource_id FROM acmr');
        $this->addSql('DROP TABLE acmr');
        $this->addSql('CREATE TABLE acmr (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, activity_id INTEGER NOT NULL, categorymaterialresource_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO acmr (id, activity_id, categorymaterialresource_id) SELECT id, activity_id, categorymaterialresource_id FROM __temp__acmr');
        $this->addSql('DROP TABLE __temp__acmr');
        $this->addSql('CREATE INDEX IDX_86173FF981C06096 ON acmr (activity_id)');
        $this->addSql('CREATE INDEX IDX_86173FF97DF85AB ON acmr (categorymaterialresource_id)');
        $this->addSql('DROP INDEX IDX_6D3A3925F3DA7551');
        $this->addSql('DROP INDEX IDX_6D3A392581C06096');
        $this->addSql('CREATE TEMPORARY TABLE __temp__ap AS SELECT id, pathway_id, activity_id, activityorder, delayminafter, delaymaxafter FROM ap');
        $this->addSql('DROP TABLE ap');
        $this->addSql('CREATE TABLE ap (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, pathway_id INTEGER NOT NULL, activity_id INTEGER NOT NULL, activityorder INTEGER NOT NULL, delayminafter INTEGER NOT NULL, delaymaxafter INTEGER NOT NULL)');
        $this->addSql('INSERT INTO ap (id, pathway_id, activity_id, activityorder, delayminafter, delaymaxafter) SELECT id, pathway_id, activity_id, activityorder, delayminafter, delaymaxafter FROM __temp__ap');
        $this->addSql('DROP TABLE __temp__ap');
        $this->addSql('CREATE INDEX IDX_6D3A3925F3DA7551 ON ap (pathway_id)');
        $this->addSql('CREATE INDEX IDX_6D3A392581C06096 ON ap (activity_id)');
        $this->addSql('DROP INDEX IDX_A6FF5DD458A652CC');
        $this->addSql('DROP INDEX IDX_A6FF5DD47DF4E972');
        $this->addSql('CREATE TEMPORARY TABLE __temp__chr AS SELECT id, humanresource_id, categoryhumanresource_id FROM chr');
        $this->addSql('DROP TABLE chr');
        $this->addSql('CREATE TABLE chr (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, humanresource_id INTEGER NOT NULL, categoryhumanresource_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO chr (id, humanresource_id, categoryhumanresource_id) SELECT id, humanresource_id, categoryhumanresource_id FROM __temp__chr');
        $this->addSql('DROP TABLE __temp__chr');
        $this->addSql('CREATE INDEX IDX_A6FF5DD458A652CC ON chr (humanresource_id)');
        $this->addSql('CREATE INDEX IDX_A6FF5DD47DF4E972 ON chr (categoryhumanresource_id)');
        $this->addSql('DROP INDEX IDX_90E2810258A652CC');
        $this->addSql('DROP INDEX IDX_90E2810297FB7789');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hri AS SELECT id, humanresource_id, indisponibility_id FROM hri');
        $this->addSql('DROP TABLE hri');
        $this->addSql('CREATE TABLE hri (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, humanresource_id INTEGER NOT NULL, indisponibility_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO hri (id, humanresource_id, indisponibility_id) SELECT id, humanresource_id, indisponibility_id FROM __temp__hri');
        $this->addSql('DROP TABLE __temp__hri');
        $this->addSql('CREATE INDEX IDX_90E2810258A652CC ON hri (humanresource_id)');
        $this->addSql('CREATE INDEX IDX_90E2810297FB7789 ON hri (indisponibility_id)');
        $this->addSql('DROP INDEX IDX_B604C73558A652CC');
        $this->addSql('DROP INDEX IDX_B604C7357CF91857');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hrsa AS SELECT id, humanresource_id, scheduledactivity_id FROM hrsa');
        $this->addSql('DROP TABLE hrsa');
        $this->addSql('CREATE TABLE hrsa (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, humanresource_id INTEGER NOT NULL, scheduledactivity_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO hrsa (id, humanresource_id, scheduledactivity_id) SELECT id, humanresource_id, scheduledactivity_id FROM __temp__hrsa');
        $this->addSql('DROP TABLE __temp__hrsa');
        $this->addSql('CREATE INDEX IDX_B604C73558A652CC ON hrsa (humanresource_id)');
        $this->addSql('CREATE INDEX IDX_B604C7357CF91857 ON hrsa (scheduledactivity_id)');
        $this->addSql('DROP INDEX IDX_D61F2C474A4B113F');
        $this->addSql('DROP INDEX IDX_D61F2C4797FB7789');
        $this->addSql('CREATE TEMPORARY TABLE __temp__imr AS SELECT id, materialresource_id, indisponibility_id FROM imr');
        $this->addSql('DROP TABLE imr');
        $this->addSql('CREATE TABLE imr (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, materialresource_id INTEGER NOT NULL, indisponibility_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO imr (id, materialresource_id, indisponibility_id) SELECT id, materialresource_id, indisponibility_id FROM __temp__imr');
        $this->addSql('DROP TABLE __temp__imr');
        $this->addSql('CREATE INDEX IDX_D61F2C474A4B113F ON imr (materialresource_id)');
        $this->addSql('CREATE INDEX IDX_D61F2C4797FB7789 ON imr (indisponibility_id)');
        $this->addSql('DROP INDEX IDX_FA49D0B47DF85AB');
        $this->addSql('CREATE TEMPORARY TABLE __temp__material_resource AS SELECT id, categorymaterialresource_id, materialresourcename, available FROM material_resource');
        $this->addSql('DROP TABLE material_resource');
        $this->addSql('CREATE TABLE material_resource (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, categorymaterialresource_id INTEGER NOT NULL, materialresourcename VARCHAR(255) NOT NULL, available BOOLEAN NOT NULL)');
        $this->addSql('INSERT INTO material_resource (id, categorymaterialresource_id, materialresourcename, available) SELECT id, categorymaterialresource_id, materialresourcename, available FROM __temp__material_resource');
        $this->addSql('DROP TABLE __temp__material_resource');
        $this->addSql('CREATE INDEX IDX_FA49D0B47DF85AB ON material_resource (categorymaterialresource_id)');
        $this->addSql('DROP INDEX IDX_EF6425D2A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__modification AS SELECT id, user_id, datemodif, modified FROM modification');
        $this->addSql('DROP TABLE modification');
        $this->addSql('CREATE TABLE modification (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, datemodif DATE NOT NULL, modified BOOLEAN NOT NULL)');
        $this->addSql('INSERT INTO modification (id, user_id, datemodif, modified) SELECT id, user_id, datemodif, modified FROM __temp__modification');
        $this->addSql('DROP TABLE __temp__modification');
        $this->addSql('CREATE INDEX IDX_EF6425D2A76ED395 ON modification (user_id)');
        $this->addSql('DROP INDEX IDX_81DA37074A4B113F');
        $this->addSql('DROP INDEX IDX_81DA37077CF91857');
        $this->addSql('CREATE TEMPORARY TABLE __temp__mrsa AS SELECT id, materialresource_id, scheduledactivity_id FROM mrsa');
        $this->addSql('DROP TABLE mrsa');
        $this->addSql('CREATE TABLE mrsa (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, materialresource_id INTEGER NOT NULL, scheduledactivity_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO mrsa (id, materialresource_id, scheduledactivity_id) SELECT id, materialresource_id, scheduledactivity_id FROM __temp__mrsa');
        $this->addSql('DROP TABLE __temp__mrsa');
        $this->addSql('CREATE INDEX IDX_81DA37074A4B113F ON mrsa (materialresource_id)');
        $this->addSql('CREATE INDEX IDX_81DA37077CF91857 ON mrsa (scheduledactivity_id)');
        $this->addSql('DROP INDEX IDX_3EE31A356B899279');
        $this->addSql('DROP INDEX IDX_3EE31A35F3DA7551');
        $this->addSql('CREATE TEMPORARY TABLE __temp__pp AS SELECT id, patient_id, pathway_id FROM pp');
        $this->addSql('DROP TABLE pp');
        $this->addSql('CREATE TABLE pp (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, patient_id INTEGER NOT NULL, pathway_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO pp (id, patient_id, pathway_id) SELECT id, patient_id, pathway_id FROM __temp__pp');
        $this->addSql('DROP TABLE __temp__pp');
        $this->addSql('CREATE INDEX IDX_3EE31A356B899279 ON pp (patient_id)');
        $this->addSql('CREATE INDEX IDX_3EE31A35F3DA7551 ON pp (pathway_id)');
        $this->addSql('DROP INDEX IDX_DDA14B8581C06096');
        $this->addSql('DROP INDEX IDX_DDA14B856B899279');
        $this->addSql('CREATE TEMPORARY TABLE __temp__scheduled_activity AS SELECT id, activity_id, patient_id, startdatetime, enddatetime FROM scheduled_activity');
        $this->addSql('DROP TABLE scheduled_activity');
        $this->addSql('CREATE TABLE scheduled_activity (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, activity_id INTEGER NOT NULL, patient_id INTEGER NOT NULL, startdatetime DATETIME NOT NULL, enddatetime DATETIME NOT NULL)');
        $this->addSql('INSERT INTO scheduled_activity (id, activity_id, patient_id, startdatetime, enddatetime) SELECT id, activity_id, patient_id, startdatetime, enddatetime FROM __temp__scheduled_activity');
        $this->addSql('DROP TABLE __temp__scheduled_activity');
        $this->addSql('CREATE INDEX IDX_DDA14B8581C06096 ON scheduled_activity (activity_id)');
        $this->addSql('CREATE INDEX IDX_DDA14B856B899279 ON scheduled_activity (patient_id)');
        $this->addSql('DROP INDEX IDX_D72CDC3D58A652CC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__working_hours AS SELECT id, humanresource_id, startdatetime, enddatetime FROM working_hours');
        $this->addSql('DROP TABLE working_hours');
        $this->addSql('CREATE TABLE working_hours (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, workinghours_id INTEGER NOT NULL, startdatetime DATETIME NOT NULL, enddatetime DATETIME NOT NULL)');
        $this->addSql('INSERT INTO working_hours (id, workinghours_id, startdatetime, enddatetime) SELECT id, humanresource_id, startdatetime, enddatetime FROM __temp__working_hours');
        $this->addSql('DROP TABLE __temp__working_hours');
        $this->addSql('CREATE INDEX IDX_D72CDC3D899D27DB ON working_hours (workinghours_id)');
    }
}
