<?php

namespace Container9mkT92N;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JxQSK8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jxQSK_8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jxQSK_8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.3Lz30ht', 'get_ServiceLocator_3Lz30htService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.h6_htL7', 'get_ServiceLocator_H6HtL7Service', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.bAgRiHP', 'get_ServiceLocator_BAgRiHPService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.VKX7spE', 'get_ServiceLocator_VKX7spEService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.brqgTzV', 'get_ServiceLocator_BrqgTzVService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.3Lz30ht', 'get_ServiceLocator_3Lz30htService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.h6_htL7', 'get_ServiceLocator_H6HtL7Service', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.bAgRiHP', 'get_ServiceLocator_BAgRiHPService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.VKX7spE', 'get_ServiceLocator_VKX7spEService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.brqgTzV', 'get_ServiceLocator_BrqgTzVService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
