<?php

namespace ContainerFBaHqxD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1n1ymiMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1n1ymiM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1n1ymiM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'circuitType' => ['privates', '.errored.Fjld16n', NULL, 'Cannot determine controller argument for "App\\Controller\\CircuitTypeController::show()": the $circuitType argument is type-hinted with the non-existent class or interface: "App\\Entity\\CircuitType".'],
        ], [
            'circuitType' => '?',
        ]);
    }
}
