<?php

namespace ContainerFBaHqxD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OXaA4_VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oXaA4.V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oXaA4.V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'resourceType' => ['privates', '.errored..service_locator.oXaA4.V.App\\Entity\\ResourceType', NULL, 'Cannot autowire service ".service_locator.oXaA4.V": it references class "App\\Entity\\ResourceType" but no such service exists.'],
            'resourceTypeRepository' => ['privates', 'App\\Repository\\ResourceTypeRepository', 'getResourceTypeRepositoryService', true],
        ], [
            'resourceType' => 'App\\Entity\\ResourceType',
            'resourceTypeRepository' => 'App\\Repository\\ResourceTypeRepository',
        ]);
    }
}
