<?php

namespace ContainerFBaHqxD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HZec6pwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HZec6pw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HZec6pw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'resourceType' => ['privates', '.errored..service_locator.HZec6pw.App\\Entity\\ResourceType', NULL, 'Cannot autowire service ".service_locator.HZec6pw": it references class "App\\Entity\\ResourceType" but no such service exists.'],
        ], [
            'resourceType' => 'App\\Entity\\ResourceType',
        ]);
    }
}
