<?php

namespace ContainerFBaHqxD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pj7ZZtiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pj7ZZti' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pj7ZZti'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'resource' => ['privates', '.errored..service_locator.pj7ZZti.App\\Entity\\Resource', NULL, 'Cannot autowire service ".service_locator.pj7ZZti": it references class "App\\Entity\\Resource" but no such service exists.'],
            'resourceRepository' => ['privates', 'App\\Repository\\ResourceRepository', 'getResourceRepositoryService', true],
        ], [
            'resource' => 'App\\Entity\\Resource',
            'resourceRepository' => 'App\\Repository\\ResourceRepository',
        ]);
    }
}
