<?php

namespace ContainerFBaHqxD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8YVWO74Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8YVWO74' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8YVWO74'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'circuitType' => ['privates', '.errored.EzoU3bl', NULL, 'Cannot determine controller argument for "App\\Controller\\CircuitTypeController::edit()": the $circuitType argument is type-hinted with the non-existent class or interface: "App\\Entity\\CircuitType".'],
            'circuitTypeRepository' => ['privates', '.errored.n.8knNE', NULL, 'Cannot determine controller argument for "App\\Controller\\CircuitTypeController::edit()": the $circuitTypeRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\CircuitTypeRepository".'],
        ], [
            'circuitType' => '?',
            'circuitTypeRepository' => '?',
        ]);
    }
}
