<?php

namespace ContainerFBaHqxD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ESMXKlZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ESMXKlZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ESMXKlZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'patient' => ['privates', '.errored..service_locator.ESMXKlZ.App\\Entity\\Patient', NULL, 'Cannot autowire service ".service_locator.ESMXKlZ": it references class "App\\Entity\\Patient" but no such service exists.'],
            'patientRepository' => ['privates', 'App\\Repository\\PatientRepository', 'getPatientRepositoryService', true],
        ], [
            'patient' => 'App\\Entity\\Patient',
            'patientRepository' => 'App\\Repository\\PatientRepository',
        ]);
    }
}
