<?php

namespace ContainerFBaHqxD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GRWhDnJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gRWhDnJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gRWhDnJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'circuitRepository' => ['privates', 'App\\Repository\\CircuitRepository', 'getCircuitRepositoryService', true],
        ], [
            'circuitRepository' => 'App\\Repository\\CircuitRepository',
        ]);
    }
}
