<?php

namespace ContainerFBaHqxD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SdyZWuD.App\Entity\Activity' shared service.
     *
     * @return \App\Entity\Activity
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SdyZWuD": it references class "App\\Entity\\Activity" but no such service exists.');
    }
}
