<?php

namespace ContainerFBaHqxD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResourceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.em6sZ1k.App\Entity\Resource' shared service.
     *
     * @return \App\Entity\Resource
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.em6sZ1k": it references class "App\\Entity\\Resource" but no such service exists.');
    }
}
