<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
if (\class_exists(\ContainerMYLTlhV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMYLTlhV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMYLTlhV.legacy');
=======
if (\class_exists(\ContainerPwZumwe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPwZumwe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPwZumwe.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
    \class_alias(\ContainerMYLTlhV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMYLTlhV\App_KernelDevDebugContainer([
    'container.build_hash' => 'MYLTlhV',
    'container.build_id' => 'a9ca5b7a',
    'container.build_time' => 1655735260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMYLTlhV');
=======
    \class_alias(\ContainerPwZumwe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPwZumwe\App_KernelDevDebugContainer([
    'container.build_hash' => 'PwZumwe',
    'container.build_id' => '6c29a131',
    'container.build_time' => 1655734037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPwZumwe');
>>>>>>> Stashed changes
