<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGi7tV3B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGi7tV3B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGi7tV3B.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGi7tV3B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGi7tV3B\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gi7tV3B',
    'container.build_id' => '5f866abe',
    'container.build_time' => 1655902588,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGi7tV3B');
