<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
<<<<<<< Updated upstream
if (\class_exists(\ContainerRndFmVx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRndFmVx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRndFmVx.legacy');
=======
if (\class_exists(\ContainerVdTUxfQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVdTUxfQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVdTUxfQ.legacy');
>>>>>>> Stashed changes
=======
if (\class_exists(\ContainerZNvYiZR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZNvYiZR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZNvYiZR.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    \class_alias(\ContainerRndFmVx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRndFmVx\App_KernelDevDebugContainer([
    'container.build_hash' => 'RndFmVx',
    'container.build_id' => '0c3c5a10',
    'container.build_time' => 1655908463,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRndFmVx');
=======
    \class_alias(\ContainerVdTUxfQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVdTUxfQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'VdTUxfQ',
    'container.build_id' => '8f509af6',
    'container.build_time' => 1655969354,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVdTUxfQ');
>>>>>>> Stashed changes
=======
    \class_alias(\ContainerZNvYiZR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZNvYiZR\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZNvYiZR',
    'container.build_id' => '553524aa',
    'container.build_time' => 1655977808,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZNvYiZR');
>>>>>>> Stashed changes
